require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
